import type { LayoutElement, LayoutJSON } from '../types/layout';

interface Props {
  page: LayoutJSON | undefined;
  selectedIds: string[];
  onChange: (updater: (layout: LayoutJSON) => LayoutJSON) => void;
  onLayer: (direction: 'up' | 'down' | 'top' | 'bottom') => void;
}

export function PropertyPanel({ page, selectedIds, onChange, onLayer }: Props) {
  const element = page?.elements.find((item) => item.id === selectedIds[0] && item.type !== 'background');
  if (!element || (element.type !== 'text' && element.type !== 'image')) return <aside className="property-panel"><div className="panel-title">元素编辑</div><div className="property-empty"><span className="property-empty-icon" aria-hidden="true">◇</span><strong>选择画布中的元素</strong><span>选中文字或图片后，在这里调整内容、位置与层级。</span></div></aside>;
  const update = (patch: Partial<LayoutElement>) => onChange((layout) => ({ ...layout, elements: layout.elements.map((item) => item.id === element.id ? { ...item, ...patch } : item) }));
  const updateStyle = (patch: Record<string, unknown>) => update({ style: { ...element.style, ...patch } });
  const numberField = (label: string, key: 'x' | 'y' | 'width' | 'height', value: number) => <label className="field"><span>{label}</span><input type="number" value={Math.round(value)} onChange={(event) => update({ [key]: Number(event.target.value) })} /></label>;
  const layerControls = <section className="property-section"><h3>层级</h3><div className="layer-actions"><button onClick={() => onLayer('up')}>上移一层</button><button onClick={() => onLayer('down')}>下移一层</button><button onClick={() => onLayer('top')}>置顶</button><button onClick={() => onLayer('bottom')}>置底</button></div></section>;
  return <aside className="property-panel"><div className="panel-title">元素编辑 <span>{element.type === 'text' ? '文本' : '图片'}</span></div>
    {element.type === 'text' && <section className="property-section"><h3>内容与样式</h3><label className="field"><span>内容</span><textarea value={element.text || ''} onChange={(event) => update({ text: event.target.value })} /></label><label className="field"><span>字体</span><input value={element.style?.fontFamily || 'Microsoft YaHei'} onChange={(event) => updateStyle({ fontFamily: event.target.value })} /></label><div className="fields-grid"><label className="field"><span>字号</span><input type="number" min="1" value={element.style?.fontSize || 24} onChange={(event) => updateStyle({ fontSize: Number(event.target.value) })} /></label><label className="field"><span>颜色</span><input type="color" value={element.style?.color || '#111827'} onChange={(event) => updateStyle({ color: event.target.value })} /></label></div><div className="segmented text-style" role="group" aria-label="文字样式"><button aria-label="粗体" aria-pressed={Number(element.style?.fontWeight || 400) >= 600} className={Number(element.style?.fontWeight || 400) >= 600 ? 'selected' : ''} onClick={() => updateStyle({ fontWeight: Number(element.style?.fontWeight || 400) >= 600 ? 400 : 700 })}><strong>B</strong></button><button aria-label="斜体" aria-pressed={element.style?.fontStyle === 'italic'} className={element.style?.fontStyle === 'italic' ? 'selected' : ''} onClick={() => updateStyle({ fontStyle: element.style?.fontStyle === 'italic' ? 'normal' : 'italic' })}><em>I</em></button></div><div className="segmented" role="group" aria-label="文字对齐"><button className={(element.style?.align || 'left') === 'left' ? 'selected' : ''} onClick={() => updateStyle({ align: 'left' })}>左对齐</button><button className={element.style?.align === 'center' ? 'selected' : ''} onClick={() => updateStyle({ align: 'center' })}>居中</button><button className={element.style?.align === 'right' ? 'selected' : ''} onClick={() => updateStyle({ align: 'right' })}>右对齐</button></div></section>}
    <section className="property-section"><h3>位置与尺寸</h3><div className="fields-grid">{numberField('X', 'x', element.x)}{numberField('Y', 'y', element.y)}{numberField('宽度', 'width', element.width)}{numberField('高度', 'height', element.height)}</div></section>
    {element.type === 'image' && <section className="property-section"><h3>裁切</h3><p className="field-hint">按图片边缘的比例裁切，0% 保留完整图片。</p><div className="fields-grid">{(['left', 'right', 'top', 'bottom'] as const).map((side) => <label className="field" key={side}><span>{{ left: '左', right: '右', top: '上', bottom: '下' }[side]}</span><input type="number" min="0" max="95" step="1" value={Math.round((element.crop?.[side] || 0) * 100)} onChange={(event) => update({ crop: { ...element.crop, [side]: Math.min(0.95, Math.max(0, Number(event.target.value) / 100)) } })} /></label>)}</div></section>}
    {layerControls}
  </aside>;
}
